config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "root#index"
  resources :games do
    resources :characters, controller: "game_characters"
    resources :npcs
    post 'set_theme/:theme_id', to: 'games#set_theme'
    get 'admin'
    resources :scenes do
      member do
        post 'set', to: 'set'
      end
    end
    resources :playlists, controller: :game_playlists
  end
  resource :home do
    post 'friends'
    post 'accept_friend/:id', to: 'users#accept_friend'
  end
  resources :friends
  resources :characters
  resources :invites, controller: :game_invites
  resources :playlists do
    resources :playlist_songs
  end
  resources :songs
end

app/models/character.rb
class Character < ActiveRecord::Base
  class Attribute
    attr_accessor :name
    attr_accessor :value
    attr_accessor :order

    def initialize(h)
      puts h.class
      @name = h["name"]
      @value = h["value"]
      @order = h["order"]
    end
  end

  belongs_to :user
  belongs_to :game, optional: true

  has_one_attached :sheet
  has_one_attached :portrait

  validates_presence_of :name

  has_many :scene_characters
  has_many :scenes, through: :scene_characters

  enum state: [ :friend, :neutral, :foe ]

  def attribute(name)
    puts(self.stats[name.to_s])
    Attribute.new(JSON.parse(self.stats[name.to_s]))  
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  enum status: [ :pending, :accepted ]

  belongs_to :owner, foreign_key: :owner_id, class_name: "User"
  belongs_to :friend, foreign_key: :friend_id, class_name: "User"

  after_create :set_pending

  validates :owner_id, uniqueness: { scope: :friend_id }
  def set_pending
    self.status = :pending
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :current_scene, foreign_key: :current_scene_id, class_name: "Scene", optional: true
  belongs_to :owner, class_name: "User"

  has_one :jukebox, dependent: :destroy

  has_many :scenes, dependent: :destroy
  has_many :characters, dependent: :destroy

  validates :name, presence: true

  has_many :game_playlists, dependent: :destroy
  has_many :playlists, through: :game_playlists
  has_many :game_invitations
  has_many :accepted_invites, -> { where(game: self, status: accepted) }, class_name: "GameInvitation"

 def players
   game_invitations.where(status: :accepted).map do |i| i.user end
 end

  def npcs
    characters.where(is_player: false)
  end

  def audio_url
     unless jukebox.nil? then
       jukebox.audio_url
      else
	   ""
     end
  end
end

app/models/game_invitation.rb
class GameInvitation < ApplicationRecord
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
  belongs_to :game
  belongs_to :user
end

app/models/game_playlist.rb
class GamePlaylist < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
end

app/models/jukebox.rb
class Jukebox < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
  after_commit :perform_job
  after_destroy :destroy_mount

  def audio_url
    config = Rails.application.config_for(:icecast)

	  "http://#{config[:hostname]}:#{config[:port]}/#{mount_point}?type=.mp3"
  end

private
  def perform_job
    JukeboxJob.perform_later(self.id)
  end

  def mount_point
    id
  end

  def destroy_mount
    config = Rails.application.config_for(:icecast)
    uri = URI.parse("http://#{config[:hostname]}:#{config[:port]}/admin/killsource").encode_www_form("mount", "/#{mountpoint})")
	  req = Net::HTTP::Get.new(uri)
	  req.basic_auth config[:user], config[:pass]
	  response = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(req)
	end
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user

  has_many :playlist_songs, dependent: :delete_all
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
  before_save :set_order

  def set_order
    if self.order.nil? then
      self.order = playlist.songs.count + 1
    end
  end

  def swap_order(other_song)
    playlist = self.playlist
    song_count = playlist.playlist_songs.count

    return if order < 0 \
           or order >= song_count
    order = other_song.order
    PlaylistSong.transaction do
      other_song.update!(order: self.order)
      self.update!(order: order)
    end
  end
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :game

  validates :name, presence: true
  validates :category, presence: true

  enum category: [ :major, :minor, :extra ]

  has_one_attached :image
  has_one_attached :audio

  has_many :scene_characters
  has_many :characters, through: :scene_characters

  def npcs
    characters.where(is_player: false)
  end
end

app/models/scene_character.rb
class SceneCharacter < ApplicationRecord
  belongs_to :character
  belongs_to :scene
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_one_attached :audio

  validates :audio, blob: { content_type: :audio }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games, foreign_key: "owner_id"
  has_many :friend_membership, foreign_key: :owner_id, class_name: "Friend"
  has_many :friends, through: :friend_membership
  has_many :friends_accepted, -> {where(friends: {status: Friend.statuses[:accepted]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"
  has_many :friends_pending, -> {where(friends: {status: Friend.statuses[:pending]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"

  has_many :characters, -> { where(is_player: true) }, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_many :game_invitations, dependent: :destroy
  has_many_attached :audio
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  layout 'game'
  helper AttachmentHelper
  before_action :authenticate_user!
  before_action :setup, except: [:new, :create]

  def index
  end

  def create
    @scene = Scene.new(scene_params)
    @scene.game_id = @game.id
    @scene.image.attach(params[:scene][:image])
    if @scene.save then
      redirect_to game_scenes_path(@game)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def new
    @scene = Scene.new
  end

  def set
    @game.update!(current_scene: @scene)
    GameChannel.broadcast_to(@game, {description: @scene.description, image: url_for(@scene.image.variant(resize_to_limit: [800, 800])), audio: url_for(@scene.audio)})
    redirect_to action: :show
    #head :no_content
  end

  def update
    if @scene.update(scene_params) then
      redirect_to game_scenes_url(@game)
    else
      render :edit
    end
  end

  def destroy
    @scene.destroy
    redirect_to request.referrer
  end

  private 

  def scene_params
    params.require(:scene).permit(:name, :description, :category, :game_id, :audio, :image)
  end

  def setup
    @game = Game.find(params[:game_id])
    @scene = Scene.find(params[:id])
  end
end

app/helpers/ValidationHelper.rb
module ValidationHelper

  def display_error(errors, field)
    #if errors
    #"<div class=invalid-feedback>Please enter a #{field}</div>".html_safe
  end

end

app/helpers/attachment_helper.rb
module AttachmentHelper
  def attachment_url(attachment)
    if attachment.attached? then
	  url_for(attachment)
	else
	 ""
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def display_character_name(user, game)
    if game.owner != user then
      character = game.characters.find_by(user: user)

      if character.nil? then
        "No Character"
      else
        link_to character.name, user_character_url(character)
      end
    else
      "Game Master"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/songs_helper.rb
module SongsHelper

  # Encodes an UploadedFile and relaces the temporary file with a new file
  # that is correctly encoded
  def encode uploaded_file
    f = File.open(EncodeService.new(params[:song][:audio].tempfile.path).encode)
    uploaded_file.tempfile.close
    FileUtils.mv(f.path, uploaded_file.path)
    uploaded_file.tempfile.open
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/scenes/_control.haml
%center
  %h1
    Scenes
  %table.table.table-dark
    %tbody
      - @game.scenes.each do |scene|
        %tr
          %th
            = button_to scene.name, set_game_scene_path(@game, scene.id), class: "btn btn-link"

app/views/scenes/_form.haml
.container{style: "width:40em;"}
  %h2 New Scene
  = form_with model: [@game, @scene], local: true do |f|
    .form-group.row.is-invalid
      .col-sm-2
        = f.label :name
      .col-sm-10
        = f.text_field :name
        = f.error_message_for(:name)
    .form-group.row.mt-3
      = f.label :description
      = f.text_area :description
      = f.error_message_for(:description)
    .form-group.row.mt-3
      = f.label :category
      = f.select(:category, Scene.categories.keys.map {|category| [category.titleize,category]})
      = f.error_message_for(:category)
    .form-group.row.mt-3
      = f.label :image
      = f.file_field :image
      = f.error_message_for(:image)
    .form-group.row.mt-3
      = f.label :audio
      = f.file_field :audio
      = f.error_message_for(:audio)
    = f.submit class: "btn btn-primary mt-5"

app/views/scenes/edit.haml
= render 'form'

app/views/scenes/index.haml
= javascript_pack_tag 'game_scene', 'data-turbolinks-track': 'reload'

.container{"data-controller": "scene"}
  .row
    .card{style: "width: 18em;margin-right:1em"}
      %img.card-img-top{src: "", width: 286, height: 180}
      .card-body
        %h5.card-title 
          = ""
        = ""
        = link_to "Create", new_game_scene_url(@game), class: "btn btn-primary"
  .row
    = render "shared/scene_card", game: @game do |scene|
      %button.btn.btn-primary.changeScene{scene: SceneBlueprint.render(scene), "data-action": "click->scene#setScene"} Change Scene
      = link_to "Edit", edit_game_scene_url(@game, scene), class: "btn btn-secondary"
      = button_to "Delete", game_scene_url(@game, scene), method: :delete, class: "btn btn-danger", style: "width: 100%;"

app/views/scenes/new.haml
= render 'form'

app/views/scenes/show.haml
.row
  .col-2{class: "container-secondary body-item mb-4", "data-controller": "scene"}
    = render "scenes/control"
  .col-8
    = hidden_field_tag(:game_id, @game.id)
    .row.d-flex.justify-content-center
    - if @scene.image.attached?
      %img.img-responsive{id: :image, src: url_for(@scene.image.variant(resize_to_limit: [800, 800]))}
    - else
      %img{id: :image, src: '', style: "min-width: 100px; min-height:100px;"}
    %p#description.mt-2
      =@scene.description || ""
    %audio#player{ controls: "", autoplay: "" }
      %source#mp3_src{ src: @audio_url, type: "audio/mp3" }
  .col-2