config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "root#index"
  resources :games do
    resources :characters, controller: "game_characters"
    resources :npcs
    post 'set_theme/:theme_id', to: 'games#set_theme'
    get 'admin'
    resources :scenes do
      member do
        post 'set', to: 'set'
      end
    end
    resources :playlists, controller: :game_playlists
  end
  resource :home do
    post 'friends'
    post 'accept_friend/:id', to: 'users#accept_friend'
  end
  resources :friends
  resources :characters
  resources :invites, controller: :game_invites
  resources :playlists do
    resources :playlist_songs
  end
  resources :songs
end

app/models/character.rb
class Character < ActiveRecord::Base
  class Attribute
    attr_accessor :name
    attr_accessor :value
    attr_accessor :order

    def initialize(h)
      puts h.class
      @name = h["name"]
      @value = h["value"]
      @order = h["order"]
    end
  end

  belongs_to :user
  belongs_to :game, optional: true

  has_one_attached :sheet
  has_one_attached :portrait

  validates_presence_of :name

  has_many :scene_characters
  has_many :scenes, through: :scene_characters

  enum state: [ :friend, :neutral, :foe ]

  def attribute(name)
    puts(self.stats[name.to_s])
    Attribute.new(JSON.parse(self.stats[name.to_s]))  
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  enum status: [ :pending, :accepted ]

  belongs_to :owner, foreign_key: :owner_id, class_name: "User"
  belongs_to :friend, foreign_key: :friend_id, class_name: "User"

  after_create :set_pending

  validates :owner_id, uniqueness: { scope: :friend_id }
  def set_pending
    self.status = :pending
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :current_scene, foreign_key: :current_scene_id, class_name: "Scene", optional: true
  belongs_to :owner, class_name: "User"

  has_one :jukebox, dependent: :destroy

  has_many :scenes, dependent: :destroy
  has_many :characters, dependent: :destroy

  validates :name, presence: true

  has_many :game_playlists, dependent: :destroy
  has_many :playlists, through: :game_playlists
  has_many :game_invitations
  has_many :accepted_invites, -> { where(game: self, status: accepted) }, class_name: "GameInvitation"

 def players
   game_invitations.where(status: :accepted).map do |i| i.user end
 end

  def npcs
    characters.where(is_player: false)
  end

  def audio_url
     unless jukebox.nil? then
       jukebox.audio_url
      else
	   ""
     end
  end
end

app/models/game_invitation.rb
class GameInvitation < ApplicationRecord
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
  belongs_to :game
  belongs_to :user
end

app/models/game_playlist.rb
class GamePlaylist < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
end

app/models/jukebox.rb
class Jukebox < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
  after_commit :perform_job
  after_destroy :destroy_mount

  def audio_url
    config = Rails.application.config_for(:icecast)

	  "http://#{config[:hostname]}:#{config[:port]}/#{mount_point}?type=.mp3"
  end

private
  def perform_job
    JukeboxJob.perform_later(self.id)
  end

  def mount_point
    id
  end

  def destroy_mount
    config = Rails.application.config_for(:icecast)
    uri = URI.parse("http://#{config[:hostname]}:#{config[:port]}/admin/killsource").encode_www_form("mount", "/#{mountpoint})")
	  req = Net::HTTP::Get.new(uri)
	  req.basic_auth config[:user], config[:pass]
	  response = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(req)
	end
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user

  has_many :playlist_songs, dependent: :delete_all
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
  before_save :set_order

  def set_order
    if self.order.nil? then
      self.order = playlist.songs.count + 1
    end
  end

  def swap_order(other_song)
    playlist = self.playlist
    song_count = playlist.playlist_songs.count

    return if order < 0 \
           or order >= song_count
    order = other_song.order
    PlaylistSong.transaction do
      other_song.update!(order: self.order)
      self.update!(order: order)
    end
  end
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :game

  validates :name, presence: true
  validates :category, presence: true

  enum category: [ :major, :minor, :extra ]

  has_one_attached :image
  has_one_attached :audio

  has_many :scene_characters
  has_many :characters, through: :scene_characters

  def npcs
    characters.where(is_player: false)
  end
end

app/models/scene_character.rb
class SceneCharacter < ApplicationRecord
  belongs_to :character
  belongs_to :scene
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_one_attached :audio

  validates :audio, blob: { content_type: :audio }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games, foreign_key: "owner_id"
  has_many :friend_membership, foreign_key: :owner_id, class_name: "Friend"
  has_many :friends, through: :friend_membership
  has_many :friends_accepted, -> {where(friends: {status: Friend.statuses[:accepted]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"
  has_many :friends_pending, -> {where(friends: {status: Friend.statuses[:pending]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"

  has_many :characters, -> { where(is_player: true) }, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_many :game_invitations, dependent: :destroy
  has_many_attached :audio
end

app/helpers/ValidationHelper.rb
module ValidationHelper

  def display_error(errors, field)
    #if errors
    #"<div class=invalid-feedback>Please enter a #{field}</div>".html_safe
  end

end

app/helpers/attachment_helper.rb
module AttachmentHelper
  def attachment_url(attachment)
    if attachment.attached? then
	  url_for(attachment)
	else
	 ""
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/songs_helper.rb
module SongsHelper

  # Encodes an UploadedFile and relaces the temporary file with a new file
  # that is correctly encoded
  def encode uploaded_file
    f = File.open(EncodeService.new(params[:song][:audio].tempfile.path).encode)
    uploaded_file.tempfile.close
    FileUtils.mv(f.path, uploaded_file.path)
    uploaded_file.tempfile.open
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_characters.haml
%table.table.table-dark
  %thead
    %tr
      %th{scope: "col"} Character
      %th{scope: "col"} Player
    %tbody
      - @game.characters.each do |character|
        %tr
          %th
            = character.name
          %th
            = character.user.email

app/views/shared/_friends.haml
- if !local_assigns[:pending]
  - friends = current_user.friends_accepted
  = form_with url: user_friends_url(current_user), local: true, class: "form-inline mb-4" do |f|
    = f.text_field :friend_uid, class: "form-control mr-sm-2"
    = f.submit "Add Friend", class: "btn btn-outline-success my-2 my-sm-0"
- else
  - friends = current_user.friends_pending
%table.table.table-dark
  %thead
    %tr
      %th{scope: "col"} Friends
      %th{scope: "col"} Remove
    %tbody
      - friends.each do |friend|
        %tr
          %th
            = friend.email
          %th
            = fa_icon "minus-circle", class: "text-danger"

app/views/shared/_game_navigation.haml
.bg-dark
  %nav.navbar.navbar-dark{style: "width:25%;"}
    = link_to "Home", home_path(current_user), class: "btn btn-link"
    = link_to "Admin", game_admin_url(@game), class: "btn btn-link"
    = link_to "Characters", new_game_npc_url(@game), class: "btn btn-link"
    = link_to "Scenes", game_scenes_url(@game), class: "btn btn-link"
    .dropdown.show
      %a.btn.btn-link.dropdown-toggle#dropdownMusicLink{role: :button, "data-toggle": :dropdown, "aria-haspopup": :true, "aria-expanded": :true}
        Music
      .dropdown-menu{"aria-labelledby": :dropdownMusicLink}
        = link_to "Music", playlists_url(@game), class: "dropdown-item"
        =# link_to "Upload", new_home_music_url(@game), class: "dropdown-item"
:javascript
  window.onclick = function(e) {
    if (e.target.matches('.dropdown-toggle')) {
      e.target.parentElement.querySelector(".dropdown-menu").style.display = "block"
    } else {
      var i;
      var elemList = document.querySelectorAll(".dropdown-toggle");
      for(i = 0; i < elemList.length; i++) {
        elemList[i].parentElement.querySelector(".dropdown-menu").style.display = "none"
      }
    }
  }

app/views/shared/_navigation.haml
.bg-dark
  %nav.navbar.navbar-dark{style: "width:25%;"}
    = link_to "Home", home_path(current_user), class: "btn btn-link"
    .dropdown.show
      %a.btn.btn-link.dropdown-toggle#dropdownCharacterLink{role: :button, "data-toggle": :dropdown, "aria-haspopup": :true, "aria-expanded": :true}
        Characters
      .dropdown-menu{"aria-labelledby": :dropdownCharacterLink}
        = link_to "New", new_character_path(current_user), class: "dropdown-item"
        = link_to "View", characters_path(current_user), class: "dropdown-item"
    = link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-link"
  :javascript
    window.onclick = function(e) {
      if (e.target.matches('.dropdown-toggle')) {
        e.target.parentElement.querySelector(".dropdown-menu").style.display = "block"
      } else {
        var i;
        var elemList = document.querySelectorAll(".dropdown-toggle");
        for(i = 0; i < elemList.length; i++) {
          elemList[i].parentElement.querySelector(".dropdown-menu").style.display = "none"
        }
      }
    }

app/views/shared/_scene_card.haml
- game.scenes.each do |scene|
  .card{style: "width: 18em;margin-right:1em"}
    %img.card-img-top{src: url_for(scene.image.variant(resize_to_limit: [286, 180])), width: 286, height: 180}
    .card-body
      %h5.card-title 
        = scene.name
      = scene.description
    = yield scene