config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "root#index"
  resources :games do
    resources :characters, controller: "game_characters"
    resources :npcs
    post 'set_theme/:theme_id', to: 'games#set_theme'
    get 'admin'
    resources :scenes do
      member do
        post 'set', to: 'set'
      end
    end
    resources :playlists, controller: :game_playlists
  end
  resource :home do
    post 'friends'
    post 'accept_friend/:id', to: 'users#accept_friend'
  end
  resources :friends
  resources :characters
  resources :invites, controller: :game_invites
  resources :playlists do
    resources :playlist_songs
  end
  resources :songs
end

app/models/character.rb
class Character < ActiveRecord::Base
  class Attribute
    attr_accessor :name
    attr_accessor :value
    attr_accessor :order

    def initialize(h)
      puts h.class
      @name = h["name"]
      @value = h["value"]
      @order = h["order"]
    end
  end

  belongs_to :user
  belongs_to :game, optional: true

  has_one_attached :sheet
  has_one_attached :portrait

  validates_presence_of :name

  has_many :scene_characters
  has_many :scenes, through: :scene_characters

  enum state: [ :friend, :neutral, :foe ]

  def attribute(name)
    puts(self.stats[name.to_s])
    Attribute.new(JSON.parse(self.stats[name.to_s]))  
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :authenticate_user!

  def show
    @character = Character.find(params[:id])
  end

  def index
    @characters = current_user.characters
  end

  def new
    @character = Character.new(user: current_user)
    @character.is_player = true
    @character.stats = [
      {"name":"strength","value":10}, 
      {"name":"dexterity","value":10}, 
      {"name":"constitution","value":10},
      {"name":"wisdom","value":10},
      {"name":"intelligence","value":10},
      {"name":"charisma","value":10}
    ]
  end

  def create
    @character = Character.new(character_params)
    @character.user = current_user
#    @character.stats = [
#      {"name":"strength","value":10}, 
#      {"name":"dexterity","value":10}, 
#      {"name":"constitution","value":10},
#      {"name":"wisdom","value":10},
#      {"name":"intelligence","value":10},
#      {"name":"charisma","value":10}
#    ]
#    i = 0
#    params[:character][:attributes].each do |k, v|
#      @character.stats[i]["value"] = v
#      i = i + 1
#    end
    if @character.save then
      redirect_to request.referrer if request.referrer
      redirect_to home_path
    else
      render :new
    end
  end

  def edit
    @character = Character.find(params[:id])
  end

  def update
    @character = Character.find(params[:id])
    i = 0
    params[:character][:attributes].each do |k, v|
      @character.stats[i]["value"] = v
      i = i + 1
    end
    if @character.save then
      redirect_to user_characters_url(current_user)
    else
      render :edit
    end
  end

  def destroy
    @character = Character.find(params[:id])
    @character.destroy
    redirect_to user_characters_url(current_user)
  end

  def character_params
    params.require(:character).permit(:name)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def display_character_name(user, game)
    if game.owner != user then
      character = game.characters.find_by(user: user)

      if character.nil? then
        "No Character"
      else
        link_to character.name, user_character_url(character)
      end
    else
      "Game Master"
    end
  end
end

app/views/characters/_form.haml
= form_with model: [@character], local: true do |f|
  .form-group.is-invalid.row.mb-2
    .col
      = f.label :name
    .col
      = f.text_field :name
    = f.error_message_for(:name)
  #skills
    - @character.stats.each do |stat|
      .form-group.is-invalid.row.mb-2
        .col
          = f.label stat["name"].to_sym
        .col
          = f.text_field "attributes[#{stat["name"]}]", value: stat["value"]
  - if not @character.is_player? then
    .form-group.row
    = f.label "Unique"
    = f.check_box :is_unique
  .form-group.row
    = f.submit class: "btn btn-primary"

app/views/characters/edit.haml
.container
  .d-flex.justify-content-center
    %h3 Edit Character
  .d-flex.justify-content-center
    = render "form"

app/views/characters/index.haml
= render "shared/navigation"
.container
  - @characters.each_slice(2) do |slice|
    .row
      - slice.each do |character|
        .character
          %h3
            = character.name
            %button.btn
            = link_to edit_character_url(current_user, character), class: "btn" do
              %i.fa.fa-edit.mr-1
            = link_to character_url(current_user, character), data: {confirm: "Are you sure?"}, method: "delete", class: "btn" do
              %i.fa.fa-trash.mr-1
            - if character.sheet.attached?
              %i.fa.fa-file
          %hr
          - if !character.stats.nil?
            %h3 Stats
            %hr
            - character.stats.each do |stat|
              .row
                .col
                  = stat["name"]
                .col
                  = stat["value"]
          - if !character.skills.nil?
            %h3 skills
            %hr
            - character.skills.each do |k, v|
              .row
                .col
                  = k
                .col
                  = v

app/views/characters/new.haml
= render "shared/navigation"
.container
  .d-flex.justify-content-center
    %h3 Create Character
  .d-flex.justify-content-center
    = render "form"

app/views/characters/show.haml
.container
  .col-md-4
    %h3
      = @character.name
      %i.fa.fa-edit
      %i.fa.fa-file
      -if @character.portrait.attached?
        = @character.portrait
    %hr
    - if !@character.stats.nil?
      %h3 Stats
      %hr
      %table.table.table-dark
        - @character.stats.each do |k|
          %tr
            %th
              = k["name"]
            %th
              = k["value"]
    - if !@character.skills.nil?
      %h3 skills
      %hr
      %table.table.table-dark
        - @character.skills.each do |k|
          %tr
            %th
              = k["name"]
            %th
              = k["value"]