config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "root#index"
  resources :games do
    resources :characters, controller: "game_characters"
    resources :npcs
    post 'set_theme/:theme_id', to: 'games#set_theme'
    get 'admin'
    resources :scenes do
      member do
        post 'set', to: 'set'
      end
    end
    resources :playlists, controller: :game_playlists
  end
  resource :home do
    post 'friends'
    post 'accept_friend/:id', to: 'users#accept_friend'
  end
  resources :friends
  resources :characters
  resources :invites, controller: :game_invites
  resources :playlists do
    resources :playlist_songs
  end
  resources :songs
end

app/models/character.rb
class Character < ActiveRecord::Base
  class Attribute
    attr_accessor :name
    attr_accessor :value
    attr_accessor :order

    def initialize(h)
      puts h.class
      @name = h["name"]
      @value = h["value"]
      @order = h["order"]
    end
  end

  belongs_to :user
  belongs_to :game, optional: true

  has_one_attached :sheet
  has_one_attached :portrait

  validates_presence_of :name

  has_many :scene_characters
  has_many :scenes, through: :scene_characters

  enum state: [ :friend, :neutral, :foe ]

  def attribute(name)
    puts(self.stats[name.to_s])
    Attribute.new(JSON.parse(self.stats[name.to_s]))  
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
  enum status: [ :pending, :accepted ]

  belongs_to :owner, foreign_key: :owner_id, class_name: "User"
  belongs_to :friend, foreign_key: :friend_id, class_name: "User"

  after_create :set_pending

  validates :owner_id, uniqueness: { scope: :friend_id }
  def set_pending
    self.status = :pending
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :current_scene, foreign_key: :current_scene_id, class_name: "Scene", optional: true
  belongs_to :owner, class_name: "User"

  has_one :jukebox, dependent: :destroy

  has_many :scenes, dependent: :destroy
  has_many :characters, dependent: :destroy

  validates :name, presence: true

  has_many :game_playlists, dependent: :destroy
  has_many :playlists, through: :game_playlists
  has_many :game_invitations
  has_many :accepted_invites, -> { where(game: self, status: accepted) }, class_name: "GameInvitation"

 def players
   game_invitations.where(status: :accepted).map do |i| i.user end
 end

  def npcs
    characters.where(is_player: false)
  end

  def audio_url
     unless jukebox.nil? then
       jukebox.audio_url
      else
	   ""
     end
  end
end

app/models/game_invitation.rb
class GameInvitation < ApplicationRecord
  enum status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }
  belongs_to :game
  belongs_to :user
end

app/models/game_playlist.rb
class GamePlaylist < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
end

app/models/jukebox.rb
class Jukebox < ApplicationRecord
  belongs_to :game
  belongs_to :playlist
  after_commit :perform_job
  after_destroy :destroy_mount

  def audio_url
    config = Rails.application.config_for(:icecast)

	  "http://#{config[:hostname]}:#{config[:port]}/#{mount_point}?type=.mp3"
  end

private
  def perform_job
    JukeboxJob.perform_later(self.id)
  end

  def mount_point
    id
  end

  def destroy_mount
    config = Rails.application.config_for(:icecast)
    uri = URI.parse("http://#{config[:hostname]}:#{config[:port]}/admin/killsource").encode_www_form("mount", "/#{mountpoint})")
	  req = Net::HTTP::Get.new(uri)
	  req.basic_auth config[:user], config[:pass]
	  response = Net::HTTP.start(uri.hostname, uri.port) do |http|
    http.request(req)
	end
  end
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user

  has_many :playlist_songs, dependent: :delete_all
  has_many :songs, through: :playlist_songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
  before_save :set_order

  def set_order
    if self.order.nil? then
      self.order = playlist.songs.count + 1
    end
  end

  def swap_order(other_song)
    playlist = self.playlist
    song_count = playlist.playlist_songs.count

    return if order < 0 \
           or order >= song_count
    order = other_song.order
    PlaylistSong.transaction do
      other_song.update!(order: self.order)
      self.update!(order: order)
    end
  end
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :game

  validates :name, presence: true
  validates :category, presence: true

  enum category: [ :major, :minor, :extra ]

  has_one_attached :image
  has_one_attached :audio

  has_many :scene_characters
  has_many :characters, through: :scene_characters

  def npcs
    characters.where(is_player: false)
  end
end

app/models/scene_character.rb
class SceneCharacter < ApplicationRecord
  belongs_to :character
  belongs_to :scene
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  has_one_attached :audio

  validates :audio, blob: { content_type: :audio }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :games, foreign_key: "owner_id"
  has_many :friend_membership, foreign_key: :owner_id, class_name: "Friend"
  has_many :friends, through: :friend_membership
  has_many :friends_accepted, -> {where(friends: {status: Friend.statuses[:accepted]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"
  has_many :friends_pending, -> {where(friends: {status: Friend.statuses[:pending]})}, through: :friend_membership, source: "owner", foreign_key: :owner_id, class_name: "User"

  has_many :characters, -> { where(is_player: true) }, dependent: :destroy
  has_many :playlists, dependent: :destroy
  has_many :songs, dependent: :destroy
  has_many :game_invitations, dependent: :destroy
  has_many_attached :audio
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(user: current_user, name: params[:playlist][:name])
    song_list = Song.find(params[:playlist][:songs])
    PlaylistSong.transaction do
      PlaylistSong.create!(song_list.map do |s| {playlist: @playlist, song: s} end)
    end
    if @playlist.save then
      redirect_to request.referrer
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @song = Song.new
    respond_to do |format|
      format.json { render json: PlaylistSongBlueprint.render(@playlist.playlist_songs.order(:order)) }
      format.html
    end
  end

  def index 
    @playlists = current_user.playlists
  end
end

app/helpers/ValidationHelper.rb
module ValidationHelper

  def display_error(errors, field)
    #if errors
    #"<div class=invalid-feedback>Please enter a #{field}</div>".html_safe
  end

end

app/helpers/attachment_helper.rb
module AttachmentHelper
  def attachment_url(attachment)
    if attachment.attached? then
	  url_for(attachment)
	else
	 ""
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
  def display_character_name(user, game)
    if game.owner != user then
      character = game.characters.find_by(user: user)

      if character.nil? then
        "No Character"
      else
        link_to character.name, user_character_url(character)
      end
    else
      "Game Master"
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/npcs_helper.rb
module NpcsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/songs_helper.rb
module SongsHelper

  # Encodes an UploadedFile and relaces the temporary file with a new file
  # that is correctly encoded
  def encode uploaded_file
    f = File.open(EncodeService.new(params[:song][:audio].tempfile.path).encode)
    uploaded_file.tempfile.close
    FileUtils.mv(f.path, uploaded_file.path)
    uploaded_file.tempfile.open
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/playlists/_empty.haml
= link_to "Add an item", new_playlist_playlist_sound_url(current_user, @playlist)

app/views/playlists/_exists.haml
.row{"data-controller": "song"}
  .col-md-3
    %div
      %span Song: 
      %span{"data-song-target": "name"}
    %div
      %span Length:
      %span{"data-song-target": "length"}
    = fa_icon "play"
    = fa_icon "pause"
  .col-md-9
    %h1 
      = @playlist.name
    %table.table.table-dark
      %thead
        %tr
          %th{scope: "col"} #
          %th{scope: "col"} Name
        %tbody
          - i = 1
          - @playlist.songs.each do |song|
            %tr{id: "song-#{song.id}"}
              %th{scope: "row"} #{i}
              %th
                = link_to song.name, "javascript:void(0);", {"data-action": "click->song#setSong", song: JSON.generate({id: song.id, name: song.name})}
              - i = i + 1
    %div
      = render "songs/form"

app/views/playlists/_form.haml
.container
  .row
    .col-4.mx-auto
      %h3{class: "text-center"} Song List
      %div.container-secondary.list#song_list{"data-controller": "list-swap", "data-list-swap-companion-value": "songs_added"}
        %span{"data-list-swap-target": "output"}
        - current_user.songs.each do |song|
          .text-center{"data-action": "click->list-swap#move"}
            = link_to song.name, "javascript:void(0)", "data-id": "song.id"
            %input{type: :hidden, name: "playlist[songs][]", value: song.id}
            %hr
    .col-4.mx-auto
      = form_with model: [current_user, @playlist], local: true, id: "form_playlist" do |f|
        .row
          .form-group
            %center
              %h1 New Playlist
          .form-group.is-invalid
            = f.label :name
            = f.text_field :name
            = f.error_message_for(:name)
          .form-group.is-invalid
        = f.submit class: "btn btn-primary mt-3"
    .col-4
      %center
        %h3 Playlist Songs
      .mx-auto.mt-3.container-secondary.list#songs_added{"data-controller": "list-swap", "data-list-swap-companion-value": "song_list"}

app/views/playlists/index.haml
= render "shared/navigation"
.container
  - if current_page?(playlists_url(current_user.id)) then
    = link_to "Create", new_playlist_url(current_user), class: "btn btn-primary col-3 mb-3"
  - else
    = link_to "Create", new_game_playlist_url, class: "btn btn-primary col-3 mb-3"
  .row{"data-controller": "playlist", "data-playlist-display-value": "playlist_display"}
    .col-6
      %table.table.table-dark.table-striped
        %thead
          %tr
            %th{scope: "col"} #
            %th{scope: "col"} Name
          %tbody#playlists
            - @playlists.each do |playlist|
              - if playlist.name.nil? then next end
              %tr{id: "playlist_#{playlist.id}", playlist_id: playlist.id}
                %th
                  = fa_icon "play", {"data-playlist-id-value": playlist.id, "data-action": "click->playlist#start"}
                %th
                  =# link_to playlist.name, playlist_url(current_user, playlist)
                  = link_to playlist.name, "javascript:void(0)", {"data-action": "click->playlist#show"}
    .col-6
      %table.table.table-dark.table-striped
        %thead
          %tr
            %th{scope: "col"} #
            %th{scope: "col"} Songs
          %tbody#playlist_display

app/views/playlists/new.haml
= render "shared/navigation"
= render 'form'

app/views/playlists/show.haml
= render "shared/navigation"
.container
  - if @playlist.songs.empty? then
    = render "empty"
  - else
    = render "exists"